version: '1'
services:
  todobackend:
	  image: todobackend
    restart: always
		# build: ./todo-app/back-end
    ports:
      - 3001:3001

  todofrontend:
	  image: todofrontend
    restart: always
		# build: ./todo-app/front-end
		depends_on:
    	- todobackend
		environment:
    	- REACT_APP_API_HOST=todobackend
    ports:
      - 3000:3000

  todotests:
	  image: todotests
    restart: always
		# build: ./todo-app/tests
		environment:
    	- FRONT_HOST=todofrontend
		depends_on:
    	- todobackend
    	- todofrontend